export { OwnerDashboard } from './pages/OwnerDashboard'
export { OwnerProperties } from './pages/OwnerProperties'
export { OwnerRegisterProperty } from './pages/OwnerRegisterProperty'
export { OwnerMaintenanceTickets } from './pages/OwnerMaintenanceTickets'
export { OwnerTenants } from './pages/OwnerTenants'
export { OwnerAnalytics } from './pages/OwnerAnalytics'
export { OwnerPayments } from './pages/OwnerPayments'
export { ownerRoutes } from './routes'
