/** Centralized route path constants for all modules */

export const ROUTES = {
  HOME: '/',

  // Auth
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
  },

  // Tenant
  TENANT: {
    ROOT: '/tenant',
    DASHBOARD: '/tenant/dashboard',
    LISTINGS: '/tenant/listings',
    PROPERTY: (id: string) => `/tenant/properties/${id}`,
    SAVED: '/tenant/saved',
    PROFILE: '/tenant/profile',
    PROPERTIES: '/tenant/properties',
    PAYMENTS: '/tenant/payments',
    PAYMENT_RECEIPT: (id: string) => `/tenant/payments/${encodeURIComponent(id)}`,
    MAINTENANCE: '/tenant/maintenance',
    MAINTENANCE_DETAIL: (id: string) => `/tenant/maintenance/${encodeURIComponent(id)}`,
    DOCUMENTS: '/tenant/documents',
    AGREEMENT: (id: string) => `/tenant/agreements/${id}`,
    ONBOARDING_PAYMENT: (id: string) => `/tenant/onboarding/${id}/payment`,
    MY_LEASE: '/tenant/my-lease',
    EXIT_NOTICE: '/tenant/exit-notice',
    NOTIFICATIONS: '/tenant/notifications',
    MESSAGES: '/tenant/messages',
    SUPPORT: '/tenant/support',
    SERIOUS_BUYER_BADGE: '/tenant/serious-buyer-badge',
    SERIOUS_BUYER_PAYMENT: '/tenant/serious-buyer-badge/payment',
  },

  // Owner
  OWNER: {
    ROOT: '/owner',
    DASHBOARD: '/owner/dashboard',
    PORTFOLIO: '/owner/portfolio',
    PROPERTY_DETAIL: (id: string) => `/owner/properties/${id}`,
    PROPERTY_EDIT: (id: string) => `/owner/properties/${id}/edit`,
    PROPERTIES: '/owner/properties',
    REGISTER_PROPERTY: '/owner/properties/register',
    MAINTENANCE: '/owner/maintenance',
    LEASES: '/owner/leases',
    LEASE_DOCUMENTS: (onboardingId: string) => `/owner/leases/${encodeURIComponent(onboardingId)}/documents`,
    TENANTS: '/owner/tenants',
    PAYMENTS: '/owner/payments',
    ANALYTICS: '/owner/analytics',
    PLANS_RULES: '/owner/plans-rules',
    PREMIUM_PAYMENT: '/owner/premium-payment',
    LISTING_PROMOTION_PAYMENT: (propertyId: string) =>
      `/owner/portfolio/promote/${encodeURIComponent(propertyId)}/payment`,
    PAYMENT_RECEIPT: (id: string) => `/owner/payments/${encodeURIComponent(id)}`,
    SETTINGS: '/owner/settings',
    NOTIFICATIONS: '/owner/notifications',
    MESSAGES: '/owner/messages',
    SUPPORT: '/owner/support',
    BROKER_PROFILE: (id: string | number) => `/owner/brokers/${id}`,
  },

  // Broker
  BROKER: {
    ROOT: '/broker',
    DASHBOARD: '/broker/dashboard',
    PORTFOLIO: '/broker/portfolio',
    PROPERTY: (id: string) => `/broker/portfolio/${id}`,
    OWNER_PORTFOLIO: (ownerId: string) => `/broker/owner-portfolio/${encodeURIComponent(ownerId)}`,
    ASSIGNED_PROPERTIES: '/broker/assigned-properties',
    LISTINGS: '/broker/listings',
    CLIENTS: '/broker/clients',
    COMMISSION: '/broker/commission',
    ANALYTICS: '/broker/analytics',
    MESSAGES: '/broker/messages',
    NOTIFICATIONS: '/broker/notifications',
    SUPPORT: '/broker/support',
    SETTINGS: '/broker/settings',
    PROFILE: '/broker/profile',
    EDIT_PROFILE: '/broker/profile/edit',
  },

  // Enterprise
  ENTERPRISE: {
    ROOT: '/enterprise',
    DASHBOARD: '/enterprise/dashboard',
    PORTFOLIO: '/enterprise/portfolio',
    PROPERTY_DETAIL: (id: string) => `/enterprise/portfolio/${id}`,
    REGISTER_PROPERTY: '/enterprise/portfolio/register',
    TEAMS: '/enterprise/teams',
    REPORTS: '/enterprise/reports',
    LEASES: '/enterprise/leases',
    ASSIGNMENT_MANAGEMENT: '/enterprise/assignments',
    BROKERS: '/enterprise/brokers',
    TENANTS: '/enterprise/tenants',
    FINANCE: '/enterprise/finance',
    MESSAGES: '/enterprise/messages',
    NOTIFICATIONS: '/enterprise/notifications',
  },

  // Admin
  ADMIN: {
    ROOT: '/admin',
    DASHBOARD: '/admin/dashboard',
    BROKER_MANAGEMENT: '/admin/broker-management',
    BROKER_PROFILE: (id: string) => `/admin/broker-management/${encodeURIComponent(id)}`,
    LISTING_MANAGEMENT: '/admin/listing-management',
    USER_MANAGEMENT: '/admin/user-management',
    FINANCE_PAYMENTS: '/admin/finance-payments',
    PAYMENT_RECEIPT: (id: string) => `/admin/finance-payments/receipt/${encodeURIComponent(id.replace(/^#/, ''))}`,
    PLATFORM_CONFIGURATION: '/admin/platform-configuration',
    APPROVAL_REQUESTS: '/admin/approval-requests',
    ASSIGNMENT_MANAGEMENT: '/admin/assignment-management',
    MAINTENANCE_TICKETS: '/admin/maintenance-tickets',
    NOTIFICATIONS: '/admin/notifications',
    MESSAGES: '/admin/messages',
    SUPPORT_QUERIES: '/admin/support-queries',
  },
} as const
